### PR TITLE
Dockerfile: update to Fedora 39

### PR DESCRIPTION
**Pull request by c4rt0**
See: https://github.com/coreos/fedora-coreos-tracker/issues/1490

### CODE REVIEW

**Review by jlebon — APPROVED** [review]

**Comment by jlebon** [comment]
To roll this out, see https://docs.fedoraproject.org/en-US/infra/sysadmin_guide/coreos-cincinnati/#_upgrades.

**Comment by c4rt0** [comment]
[PR](https://pagure.io/fedora-infra/ansible/pull-request/1843) with the update to the fedora-infra/ansible repository

**Comment by c4rt0** [comment]
> To roll this out, see https://docs.fedoraproject.org/en-US/infra/sysadmin_guide/coreos-cincinnati/#_upgrades.

This is now complete.

**Comment by c4rt0** [comment]
@jlebon - how do I verify that the target commit has been successfully built into a container image?

**Comment by jlebon** [comment]
You can log into the OpenShift instance, switch to the `coreos-cincinnati` project (`oc project ...`), and then inspect the build that was triggered (`oc get builds`, `oc logs build/...`) and verify that the pod is up and happy (`oc get pods`, `oc logs ...`).

**Pull request merged**
