### PR TITLE
fedora-infra/Dockerfile: Update to fedora 39

### PR DESCRIPTION
**Pull request by travier**
See: https://github.com/coreos/fedora-coreos-tracker/issues/1490

### CODE REVIEW

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
There might be some more steps needed than just merging this PR to roll this out in the infra.

**Comment by dustymabe** [comment]
If there are we should add those steps to the rebase checklist: https://github.com/coreos/fedora-coreos-tracker/blob/main/.github/ISSUE_TEMPLATE/rebase.md

**Comment by jlebon** [comment]
Yes, it's documented at https://docs.fedoraproject.org/en-US/infra/sysadmin_guide/coreos-cincinnati/#_upgrades.

**Comment by c4rt0** [comment]
Sorry @travier - I missed this PR when creating my own. This has been already merged [here](https://github.com/coreos/fedora-coreos-cincinnati/blob/main/dist/fedora-infra/Dockerfile#L1)
We can close this PR.

**Pull request closed without merging**
